# Generated by Django 4.0.4 on 2022-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_text', '0002_usershistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail',
            field=models.CharField(default='null', max_length=16),
        ),
    ]
