# Generated by Django 4.0.4 on 2022-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_text', '0004_remove_userinfo_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
